[package]
name = "mastr-energy-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "^0.11", features = ["json", "blocking"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
